spring.application.name=slit-project-spring


spring.datasource.url=jdbc:mysql://localhost:3306/mysliitdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
springdoc.swagger-ui.path=swagger-ui.index.html



file.upload-path=uploads/property-images



spring.web.resources.static-locations=classpath:/static/,file:uploads/
